pip install --upgrade pip;
pip install torch==1.7.0 torchvision==0.8.1;
pip install timm==0.3.2;
pip install cupy-cuda101;
pip install torchprofile;
pip install einops;
pip install tensorboardX;
pip install yapf;
pip install cython;
pip install opencv-python;
pip install pytest-runner;
pip install terminaltables;
pip install mmpycocotools;
pip install packaging==21.0;
pip install mmcls==0.21.0;
pip install mmcv-full==1.4.4;